### ISSUE TITLE
DCERPC Service Control Manager Methods

### ISSUE THREAD

**Issue by thelightcosine** [rapid7/ruby_smb#101]
Once DCERPC basics are implemented, we need to implement a DCERPC Service Control Manager abstraction that will allow us to Create, Start, and Stop Services on the remote server. This is critical for PSExec capabaility

**Comment by cdelafuente-r7** [comment]
I'm closing this since it has been implemented [here](https://github.com/rapid7/ruby_smb/blob/master/lib/ruby_smb/dcerpc/svcctl.rb).
