### ISSUE TITLE
About Timeout?

### ISSUE THREAD

**Issue by Lucifer1993** [rapid7/ruby_smb#115]
Dear, When I use ruby_smb to connet server which 445 port closed,how to set timeout by myself.If not,the prog will still hang on.

**Comment by chrisdlf** [comment]
Hello Lucifer1993,
You can setup the connect timeout on the socket before passing it to the Dispatcher:
```ruby
sock = Socket.tcp(address, 445, connect_timeout: 10)
dispatcher = RubySMB::Dispatcher::Socket.new(sock)
```

**Comment by Lucifer1993** [comment]
Thanks very much!!
