### ISSUE TITLE
Add NDR types

### ISSUE THREAD

**Issue by dmohanty-r7** [rapid7/ruby_smb#124]
Define structures for the NDR types pertaining to NetShareEnum as described by @chrisdlf https://github.com/rapid7/ruby_smb/pull/118#discussion-diff-161909063R32

This will include Top-level Full Pointers, Conformant and Varying Strings. The results from the NetShareEnumAll request should be parsed with defined NDR structures which will be used in other dcerpc calls.

**Comment by cdelafuente-r7** [comment]
I'm closing this since many [NDR structures](https://github.com/rapid7/ruby_smb/blob/master/lib/ruby_smb/dcerpc/ndr.rb) were implemented since then. If the need arises, we can just create new issues for NDR structure feature requests.
