### ISSUE TITLE
Invalid SMB packet?

### ISSUE THREAD

**Issue by bwatters-r7** [rapid7/ruby_smb#153]
From reading this over, I think that this framework issue belongs here:
https://github.com/rapid7/metasploit-framework/issues/11313

**Comment by cdelafuente-r7** [comment]
Apparently, this has been fixed in the last version of `ruby_smb` (see my comment [here](https://github.com/rapid7/metasploit-framework/issues/11313#issuecomment-590459549))

**Comment by cdelafuente-r7** [comment]
I'm closing this issue since it has been fixed now. Please, feel free to reopen it if you experience the problem again.
