### ISSUE TITLE
STATUS_LOGON_FAILURE

### ISSUE THREAD

**Issue by Fcukit** [rapid7/ruby_smb#159]
I try connect to smb server via Mac OS Finder with path `smb://192.168.8.22/backup$/webcluster-backup` and `username:pass smb-admin:smb-pass`, and it is success. But via ruby script from examples folder I get fail messages.

`ruby test_smb.rb 192.168.8.22 smb-admin smb-pass backup$\\a-cluster-backup backup_folder`

_SMB3 : (0xc000006d) STATUS_LOGON_FAILURE: The attempted logon is invalid. This is either due to a bad username or authentication information.
Failed to connect to `smb:\\192.168.8.22\backup$\a-cluster-backup`: Communication error with the remote host: An error occurred reading from the Socket Connection reset by peer. The server supports encryption but was not able to handle the encrypted request._

**Comment by smcintyre-r7** [comment]
What version of Ruby SMB are you using and what is the remote SMB service running on? Is it Mac OS as well, Samba something else? Would you be able to provide a pcap of the traffic when this error occurs?

**Comment by cdelafuente-r7** [comment]
Also, I don't think `test_smb.rb` script exists in the `examples/` folder. Please, can you share its content (if possible)?

Most of the scripts in `examples/` need the share separated from the file path:
```
ruby read_file.rb <ip address> <username> <passwd> <SHARE> <path/to/file>
```
So here, depending on what this script does, this syntax might fix the issue:
```
ruby test_smb.rb 192.168.8.22 smb-admin smb-pass backup$ webcluster-backup/your_file
```
