### ISSUE TITLE
Stripping leading "/"s from RPC service names is not unconditionally the right thing

### ISSUE THREAD

**Issue by charles-dyfis-net** [rapid7/ruby_smb#161]
Communicating with Samba 3.5.0, invoking `srvsvc` via `IPC$` succeeds with a leading backslash on the pipe name, thus `\srvsvc` (which is how `rpcclient` distributed with Samba does it); but fails (with a `STATUS_OBJECT_NAME_NOT_FOUND`) with that backslash stripped.

Because `RubySMB::Client::Utils#create_pipe` unconditionally strips backslashes from the pipe name, it cannot be used for RPC communication with a version of Samba that has this behavior.

If this behavior is ever necessary, it should be made optional. (This is the other bug I had to work around, besides rapid7/metasploit-framework#13976, to successfully execute `is_known_pipename` against samba 3.5.0 from a current metasploit dev build).

**Comment by cdelafuente-r7** [comment]
I'm closing this issue since this has been fixed in https://github.com/rapid7/ruby_smb/pull/163. Please, feel free to reopen it if you still experience this issue.
