### ISSUE TITLE
Query Alignment Info

### ISSUE THREAD

**Issue by jlee-r7** [rapid7/ruby_smb#22]
https://msdn.microsoft.com/en-us/library/cc232065.aspx

Also [MSDN 2.2.37 SMB2 QUERY_INFO Request](https://msdn.microsoft.com/en-us/library/cc246557.aspx)

**Comment by limhoff-r7** [comment]
As an SMB2 user I want to query alignment info so that I only use Dark Side files so I can get Force Lightning sooner.

**Comment by Meatballs1** [comment]
:facepunch:
