### ISSUE TITLE
Remove use of double exclamation in code

### ISSUE THREAD

**Issue by gwillcox-r7** [rapid7/ruby_smb#225]
More of a question than anything but is there a reason that https://github.com/rapid7/ruby_smb/blob/master/lib/ruby_smb/server/server_client/session_setup.rb#L83 uses the `!!` syntax? I can't find a legitimate reason for this apart from if the object returned was expected to be an empty string in which case this would convert it into its boolean expression (in which case a converter method like .to_s or similar might be more appropriate imho). Furthermore the function appears to be expected to return a boolean already 😕  Could someone explain if I'm missing something or if this is a case of poor programming practice?

**Comment by smcintyre-r7** [comment]
`!!` will convert the value to a boolean.
