### ISSUE TITLE
Warn when connecting to non-Smb2 enabled server

### ISSUE THREAD

**Issue by jlee-r7** [rapid7/ruby_smb#43]
maybe raise?

**Comment by jlee-r7** [comment]
Looks like Server 2003 just times out when you send a SMB2 Negotiate packet, so... no real easy way to tell that it's not supported without the multi-proto negotiate.  =(

**Comment by asolino** [comment]
AFAIK [MS-SMB2] section 1.7 is the only way to reliably do this. (SMB1 `SMB_COM_NEGOTIATE` packet with `NT LM 0.12`, `SMB 2.002` and `SMB 2.???` dialects,  and check the answer is a SMB2 packet)
hope this helps.
