### ISSUE TITLE
EternalBlue support

### ISSUE THREAD

**Issue by zerosum0x0** [rapid7/ruby_smb#89]
EB module is now in master repo. Here are some of the things that can be ported.

- anonymous logins
- SMB1 NT Trans request packet is needed.
- client.peer_native_os 

Let me know if I can provide more info. This can be found by running EternalBlue and getting a PCAP, it's the first few SMB packets.

The random IP was coincidental. It's known for weeks EB can be replayed from any pcap of FuzzBunch, of which there are many available.

**Comment by zerosum0x0** [comment]
There was also another issue where I got an unhandled exception when I got a STATUS_LOGON_FAILURE and it still wanted to connect to IPC$.

```
Error: undefined method `name' for nil:NilClass
/home/rs/.rvm/gems/ruby-2.4.1@metasploit-framework/gems/ruby_smb-0.0.12/lib/ruby_smb/client/tree_connect.rb:40:in `smb1_tree_from_response'

```

**Comment by dmaloney-r7** [comment]
@zerosum0x0 I'm actually finishing up NT Transact right now. I'll look into the Anonymous login right after that
